
project_id = "jffgmefblqiwmoputeeq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true

[functions.send-email]
verify_jwt = false

