
import axios from 'axios';

// Anyscale API configuration
const ANYSCALE_API_URL = 'https://api.endpoints.anyscale.com/v1/chat/completions';
const MODEL = 'mistralai/Mixtral-8x7B-Instruct-v0.1';

interface AnyscaleResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: {
    index: number;
    message: {
      role: string;
      content: string;
    };
    finish_reason: string;
  }[];
}

/**
 * Function to generate AI response using Anyscale API
 * @param prompt The prompt to send to the model
 * @returns The generated text response
 */
export const generateOllamaResponse = async (prompt: string): Promise<string> => {
  try {
    console.log('Sending request to Anyscale API with prompt:', prompt);
    
    // For development and testing, if API is not available, use a fallback response
    if (process.env.NODE_ENV === 'development' && !process.env.ANYSCALE_API_KEY) {
      console.log('Using fallback response for development');
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 1000));
      return `This is a fallback response for development purposes. In production, this would be generated by the Anyscale API using the prompt: "${prompt}"`;
    }
    
    // You should replace this with your actual API key
    const apiKey = 'YOUR_ANYSCALE_API_KEY'; // This should be stored in environment variables
    
    const response = await axios.post<AnyscaleResponse>(ANYSCALE_API_URL, {
      model: MODEL,
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant that generates high-quality blog content and writing assistance."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 2000,
    }, {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      }
    });
    
    console.log('Received response from Anyscale API');
    return response.data.choices[0].message.content;
  } catch (error) {
    console.error('Error generating Anyscale response:', error);
    
    // Provide a graceful fallback for errors
    return "I'm sorry, I couldn't generate a response at this time. Please try again later.";
  }
};

/**
 * Rewrites a paragraph using Anyscale API
 * @param text Original paragraph text
 * @param tone Desired tone for rewrite
 * @returns Rewritten paragraph
 */
export const rewriteParagraphWithOllama = async (text: string, tone: string): Promise<string> => {
  const prompt = `Rewrite the following paragraph in a ${tone} tone, maintaining its meaning but using different wording:\n\n"${text}"\n\nRewritten paragraph:`;
  return generateOllamaResponse(prompt);
};

/**
 * Rewrites a sentence using Anyscale API
 * @param text Original sentence text
 * @param tone Desired tone for rewrite
 * @returns Rewritten sentence
 */
export const rewriteSentenceWithOllama = async (text: string, tone: string): Promise<string> => {
  const prompt = `Rewrite the following sentence in a ${tone} tone, maintaining its meaning but using different wording:\n\n"${text}"\n\nRewritten sentence:`;
  return generateOllamaResponse(prompt);
};

/**
 * Generates blog ideas using Anyscale API
 * @param topic Blog topic
 * @param count Number of ideas to generate
 * @returns List of blog ideas
 */
export const generateBlogIdeasWithOllama = async (topic: string, count: number): Promise<string[]> => {
  const prompt = `Generate ${count} unique and engaging blog post ideas about "${topic}". For each idea, provide a compelling title.`;
  const response = await generateOllamaResponse(prompt);
  
  // Parse the response into a list of blog ideas
  const ideas = response
    .split(/\d+\./)
    .map(item => item.trim())
    .filter(item => item.length > 0);
  
  return ideas.length ? ideas : [`${count} Blog Ideas About ${topic}`];
};
