// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jffgmefblqiwmoputeeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZmdtZWZibHFpd21vcHV0ZWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mzc2OTYsImV4cCI6MjA1OTAxMzY5Nn0.MMsZwvd3FV3ghtBc3d7hl3m8U06YQIfa205IQBM8yIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);